$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: huggingface-environment
image: mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference:latest
conda_file: conda.yml